CREATE TABLE IF NOT EXISTS "counts" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	"url"	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "urls" (
	"url"	TEXT,
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	"count"	INTEGER DEFAULT 0
);